/*
 * settings.h
 *
 *  Created on: Sep 8, 2023
 *      Author: luker
 */

#ifndef INC_SETTINGS_H_
#define INC_SETTINGS_H_

#include <stdint.h>

#define DX_ETH2USB__USB_DEVICE__PRIMARY_ENDPOINT_NO 2
#define DX_ETH2USB__USB_DEVICE__PRIMARY_PIPE_NO 1
#define DX_ETH2USB__USB_DEVICE__MAX_PACKET_SIZE 64

#define DX_ETH2USB__USB_DEVICE__VALIDATE_VENDOR_ID_AND_PRODUCT_ID
#define DX_ETH2USB__USB_DEVICE__VENDOR_ID 0x16C1
#define DX_ETH2USB__USB_DEVICE__PRODUCT_ID 0x2664

#define DX_ETH2USB__STATE_MACHINE__USB_EVENT_MAX_MSG_CNT 4

#define DX_ETH2USB__STATUS__ETHERNET_BLINK_INTERVAL 300
#define DX_ETH2USB__STATUS__USB_BLINK_INTERVAL 300

#endif /* INC_SETTINGS_H_ */
